name: pymongo_demo

channels:
  - conda-forge
  - nodefaults

dependencies:
  # runtime dependencies
  - python >=3.6,<3.11.0
  - jupyterlab >=3.0.0,<4.0.0
  - pip
  - pymongo >=4
  - nodejs
  - pip:
    - mtools