name: Python Wheels

on:
  push:
    branches: ["main"]
    tags:
      - "**"
  pull_request:
  workflow_dispatch:

concurrency:
  group: wheels-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -eux {0}

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.python }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        # Github Actions doesn't support pairing matrix values together, let's improvise
        # https://github.com/github/feedback/discussions/7835#discussioncomment-1769026
        buildplat:
        - [ubuntu-20.04, manylinux_x86_64]
        - [ubuntu-20.04, manylinux_aarch64]
        - [ubuntu-20.04, manylinux_ppc64le]
        - [ubuntu-20.04, manylinux_s390x]
        - [ubuntu-20.04, manylinux_i686]
        - [macos-11, macosx_*]
        - [windows-2019, win_amd64]
        - [windows-2019, win32]
        python: ["cp37", "cp38", "cp39", "cp310", "cp311", "cp312"]

    steps:
      - name: Checkout pymongoarrow
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up python version
        run: |
          export PYTHON_VERSION=$(sed 's/^cp3/3./' <<< ${{ matrix.python }} )
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV

      - uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
          allow-prereleases: true

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Install cibuildwheel
        run: python -m pip install "cibuildwheel>=2.4,<3"

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
          MACOSX_DEPLOYMENT_TARGET: "10.14"

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python }}-${{ startsWith(matrix.buildplat[1], 'macosx') && 'macosx' || matrix.buildplat[1] }}
          path: ./wheelhouse/*.whl
          if-no-files-found: error

  make_sdist:
    name: Make SDist
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          # Build sdist on lowest supported Python
          python-version: '3.7'

      - name: Build SDist
        run: |
          set -ex
          python -m pip install -U pip build
          python -m build --sdist .

      - name: Test Sdist
        run: |
          python -m pip install dist/*.gz
          cd ..
          python -c "from pymongo import has_c; assert has_c()"

      - uses: actions/upload-artifact@v3
        with:
          name: "sdist"
          path: ./dist/*.tar.gz

  collect-dist:
    runs-on: ubuntu-latest
    needs: [build_wheels, make_sdist]
    name: Download Wheels
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Flatten directory
        working-directory: .
        run: |
          find . -mindepth 2 -type f -exec mv {} . \;
          find . -type d -empty -delete
      - uses: actions/upload-artifact@v3
        with:
          name: pymongo-all-dist-${{ github.head_ref || github.ref_name }}
          path: "./*"
