name: Python Wheels

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.post[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+[a-b][0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"
  workflow_dispatch:
  pull_request:

concurrency:
  group: wheels-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -eux {0}

jobs:
  generate_sarif_report:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: "Export SARIF file from code scanning alerts"
        uses: "alcaeus/drivers-github-tools/code-scanning-export@export-code-scanning-report"

      - name: "Attach generated SARIF file to build artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: code-scanning-alerts.json
          path: code-scanning-alerts.json
          retention-days: 3
